config/routes.rb
Collectrbot::Application.routes.draw do
  get '/pages' => 'pages#index'
  get '/pages/find' => 'pages#find'
  put '/pages/:id/trash' => 'pages#trash'
  post '/pages/trash' => 'pages#trash', as: "trash_all_pages"
  put '/pages/:id/archive' => 'pages#archive'
  post '/pages/archive' => 'pages#archive', as: "archive_all_pages"
  put '/pages/:id/favorite' => 'pages#favorite'
  put '/pages/:id/share' => 'pages#share'
  post 'pages/empty' => 'pages#empty', as: "empty_trash"
  
  devise_for :users
  
  resources :users do
    member do
      put :subscribe
      put :unsubscribe
    end
  end
  
  post 'api/pages' => 'api_pages#create'
  get 'api/login' => 'api_sessions#create'
  
  get '/help' => 'misc#help'
  
  root to: 'pages#index'
  
  get '/:id' => 'users#show', as: 'vanity'
end

app/models/user.rb
class User < ActiveRecord::Base
  # :username, :email, :password, :password_confirmation, :remember_me, :limited
  
  def to_param
    username
  end
  
  default_scope order('id ASC')
  
  DISALLOWED_USERNAMES = ["pages", "users", "api"]
  
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :pages
  
  has_many :subscription_records, class_name: "Subscription", foreign_key: "subscriber_id"
  has_many :subscriber_records, class_name: "Subscription", foreign_key: "subscribed_id"
  
  has_many :subscriptions, through: :subscription_records, source: :subscribed, conditions: ["subscriptions.approved is not ?", nil]
  has_many :subscribers, through: :subscriber_records, source: :subscriber, conditions: ["subscriptions.approved is not ?", nil]
  
  has_many :pending_subscriptions, through: :subscription_records, source: :subscribed, conditions: ["subscriptions.approved is ?", nil]
  has_many :pending_subscribers, through: :subscriber_records, source: :subscriber, conditions: ["subscriptions.approved is ?", nil]
  
  before_save do
    if DISALLOWED_USERNAMES.include?(username)
      errors.add :base, "Username not allowed."
    end
  end
  
  def limited?() limited.nil? ? false : true end
  
  def encrypted_id(password)
    BCrypt::Engine::hash_secret(email+password, Rails.application.config.secret_token)
  end
  
  def subscription(user) return subscription_records.find_by_subscriber_id_and_subscribed_id(self.id, user.id) end
  def subscribed?(user) subscription(user).present? end
  def subscribe!(user)
    unless subscribed?(user)
      Subscription.create!(subscriber_id: self.id, subscribed_id: user.id)
    end
  end
  def unsubscribe!(user)
    sub = subscription(user)
    sub.destroy if sub
  end
  def approve_subscriber(user)
    subscriber_records.find_by_subscriber_id_and_subscribed_id(user.id, self.id).approve!
  end
  
  def wipe_clean(user_token)
    Subscription.where("subscriber_id = ? or subscribed_id = ?", self.id, self.id).destroy_all
    UserPage.where("user_id = ? or user_id = ?", self.id, user_token).destroy_all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /users/1
  def show
    @user = User.find_by_username(params[:id])
    pages = UserPage.joins("LEFT JOIN pages on pages.id = user_pages.page_id")
      .select("user_pages.*, pages.title, pages.url, pages.id as page_id")
      .where("user_pages.user_id = ?", @user.id.to_s)
      .where("shared is not ?", nil)
      .order("user_pages.id DESC")
      .limit(1000)
      .to_a
    @pages = unflatten(pages, "domain")
    @viewing = @user.username
    @left_panel = :feeds
  end

  # GET /users/1/edit  
  def edit
    @viewing = params[:v] || "username"
    if @viewing == "delete"
      render "delete"
    end
    @left_panel = :account
  end
  
  # PUT /users/1
  def update
    if params[:user][:current_password].blank?
      flash[:error] = "You must verify current password to save changes."
    else
      current_user.update_attributes(params[:user])
    end
    redirect_to edit_user_path(current_user), success: "Update successful."
  end
  
  def destroy
    current_user.wipe_clean
    current_user.destroy
    redirect_to root_url
  end
  
  def subscribe
    followed_user = User.find_by_username(params[:id])
    current_user.subscribe!(followed_user)
    redirect_to followed_user
  end
  
  def unsubscribe
    followed_user = User.find_by_username(params[:id])
    current_user.unsubscribe!(followed_user)
    redirect_to followed_user
  end
  
  def approve
    current_user.approve_subscriber!(User.find_by_username(params[:id]))
  end
  
  private
  
  def show_settings_nav
    @show_nav = true
  end
end

app/views/users/delete.html.haml
#users
  %h3 Deleting your Account
  
  %p 
    Once you delete your account, we will delete all records associated with you.
    These records will not be retrievable if you decide to change your mind.
  %p
    If you'd like to keep your records, but would like to keep them private, you can! 
    Go to the settings tab and set your account status to limited. 
    Only you and those that you have allowed to follow you will be able to see your shared pages.
  %p
    Still want to delete your account? Hit the delete button below, and click through one last confirmation.
  %p
    We'll miss you!
  %p
    = link_to "Delete My Account", current_user, class: "btn btn-danger", method: "delete", confirm: "Are you absolutely certain?"

app/views/users/edit.html.haml
#users
  %h3 Account Settings
  = form_for current_user, html: { class: "form-horizontal" } do |f|
    - if @viewing == "username"
      .control-group
        %label.control-label Username
        .controls
          = f.text_field :username
    - elsif @viewing == "emailpwd"
      .control-group
        %label.control-label Email
        .controls
          = f.text_field :email
      .control-group
        %label.control-label Current Password
        .controls
          = f.text_field :password
      .control-group
        %label.control-label New Password
        .controls
          = f.text_field :password
      .control-group
        %label.control-label Confirm New Password
        .controls
          = f.text_field :password
    - elsif @viewing == "settings"
      %p 
        You can limit access your Shared stream so that only your approved friends can view it. 
      %p
        Whether you limit access or not, no one will ever be able to see your deleted, archived or favorited pages.
        Only shared pages will ever be visible.
      .control-group
        .controls
          %label.checkbox
            = f.check_box :limited
            Limit access to your posts
    .control-group
      .controls
        = f.submit "Save", class: "btn"

app/views/users/show.html.haml
- if @user == current_user
  = link_to "Edit Profile", edit_user_path(current_user), class: "btn", style: "float: right;"
- elsif not current_user.subscribed?(@user)
  = link_to "Follow", subscribe_user_path(@user), class: "btn", style: "float:right", method: "put"
- else
  = link_to "Following", unsubscribe_user_path(@user), class: "btn btn-info", style: "float:right", method: "put"
  
%h2= @user.username
#index{ style: "text-align: center;" }
  %ul{ style: "padding-top: 10px;" }
    - if @user.limited? and not current_user.subscribed?(@user)
      %p This user has a limited profile. You must be approved to follow them in order to see their shared pages.
    - else
      - @pages.each do |page_group|
        - if page_group.size == 1
          = render "pages/page", page: page_group.first
        - else
          = render "pages/page_group", page_group: page_group