config/routes.rb
Collectrbot::Application.routes.draw do
  get '/pages' => 'pages#index'
  get '/pages/find' => 'pages#find'
  put '/pages/:id/trash' => 'pages#trash'
  post '/pages/trash' => 'pages#trash', as: "trash_all_pages"
  put '/pages/:id/archive' => 'pages#archive'
  post '/pages/archive' => 'pages#archive', as: "archive_all_pages"
  put '/pages/:id/favorite' => 'pages#favorite'
  put '/pages/:id/share' => 'pages#share'
  post 'pages/empty' => 'pages#empty', as: "empty_trash"
  
  devise_for :users
  
  resources :users do
    member do
      put :subscribe
      put :unsubscribe
    end
  end
  
  post 'api/pages' => 'api_pages#create'
  get 'api/login' => 'api_sessions#create'
  
  get '/help' => 'misc#help'
  
  root to: 'pages#index'
  
  get '/:id' => 'users#show', as: 'vanity'
end

app/views/pages/_form.html.haml
= form_for @page, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :url, :class => 'control-label'
    .controls
      = f.text_area :url, :class => 'text_area'
  .control-group
    = f.label :content, :class => 'control-label'
    .controls
      = f.text_area :content, :class => 'text_area'
  .control-group
    = f.label :viewed, :class => 'control-label'
    .controls
      = f.number_field :viewed, :class => 'number_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), pages_path, :class => 'btn'

app/views/pages/_page.html.haml
%li.item
  .page{ style: "text-align: center;" }
    %h3= link_to (page.title || "Mystery Page"), page.url, target: "_blank"
    %h5= link_to page.sub_url, page.url, target: "_blank"
    %h6= page.domain + ", Viewed for #{timeish(page.viewed)}, " + time_ago_in_words(page.updated_at) + " ago"
  .actions{ data: { id: page.page_id } }
    %i.icon.icon-cancel.trash{ onclick: "$.CB.Pages.updatePage(this, 'trash')", title: "Trash" }
    %i.icon.icon-key.archive{ onclick: "$.CB.Pages.updatePage(this, 'archive')", title: "Archive"  }
    %i.icon.icon-upload-cloud.share{ onclick: "$.CB.Pages.updatePage(this, 'share')", title: "Share"  }
    %i.icon.icon-heart-empty.favorite{ onclick: "$.CB.Pages.updatePage(this, 'favorite')", title: "Favorite"  }

app/views/pages/_page_group.html.haml
%li.item
  .page{ style: "text-align: center;" }
    - first_page = page_group.first
    - viewed = 0
    %h3= link_to (first_page.title || "Mystery Page"), first_page.domain
  
    - page_group.each do |page|
      %h5= link_to (page.title.blank? or page.title == first_page.title) ? page.sub_url : page.title, page.url
      - viewed += page.viewed.to_i
  
    %h6= first_page.domain + ", Viewed for #{timeish(viewed)}, " + time_ago_in_words(first_page.updated_at) + " ago"
  
  .actions{ data: { ids: page_group.collect(&:page_id) } }
    %i.icon.icon-cancel{ onclick: "$.CB.Pages.updateGroup(this, 'trash')", title: "Trash All" }
    %i.icon.icon-key{ onclick: "$.CB.Pages.updateGroup(this, 'archive')", title: "Archive All" }
    %i.icon.icon-resize-full-alt{ onclick: "$.CB.Pages.expand(this);", title: "Expand list" }
  
  %ul.page_group
    - page_group.each do |page|
      = render "pages/page", page: page

app/views/pages/edit.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/pages/index.html.haml
:javascript
  $(function(){ $("#search_input").autocomplete($.CB.Pages.searchOptions) });

#index{ style: "text-align: center;" }
  - if @viewing == "new" or @viewing == "trash"  
    .btn-group{ style: "float: right;" }
      %a.btn.dropdown-toggle{ data: { toggle: "dropdown" } }
        More
        %span.caret
      %ul.dropdown-menu
        - if @viewing == "new"
          %li= link_to "Archive All", archive_all_pages_path(ids: "all"), method: "post"
          %li= link_to "Trash All", trash_all_pages_path(ids: "all"), method: "post"
        - elsif @viewing == "trash"
          %li= link_to "Empty Trash", empty_trash_path, method: "post", confirm: "Are you sure you want to delete everything in your Trash folder?"
      
  #search.form.form-search
    .input-append{ style: "width: 60%;" }
      %input#search_input.search-query.input-block-level{ type: "text", autocomplete: "Off" }
      %span.add-on{ style: "border-radius: 0 14px 14px 0;" }
        %i.icon.icon-search
  
  #search_results
    %ul
  
  %ul{ style: "padding-top: 10px;" }
    - @pages.each do |page_group|
      - if page_group.size == 1
        = render "page", page: page_group.first
      - else
        = render "page_group", page_group: page_group

app/views/pages/new.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/pages/show.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:url) + ':'
  %br
  = @page.url
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @page.content
%p
  %strong= model_class.human_attribute_name(:viewed) + ':'
  %br
  = @page.viewed
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @page.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), pages_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_page_path(@page), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), page_path(@page), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'