config/routes.rb
Collectrbot::Application.routes.draw do
  get '/pages' => 'pages#index'
  get '/pages/find' => 'pages#find'
  put '/pages/:id/trash' => 'pages#trash'
  post '/pages/trash' => 'pages#trash', as: "trash_all_pages"
  put '/pages/:id/archive' => 'pages#archive'
  post '/pages/archive' => 'pages#archive', as: "archive_all_pages"
  put '/pages/:id/favorite' => 'pages#favorite'
  put '/pages/:id/share' => 'pages#share'
  post 'pages/empty' => 'pages#empty', as: "empty_trash"
  
  devise_for :users
  
  resources :users do
    member do
      put :subscribe
      put :unsubscribe
    end
  end
  
  post 'api/pages' => 'api_pages#create'
  get 'api/login' => 'api_sessions#create'
  
  get '/help' => 'misc#help'
  
  root to: 'pages#index'
  
  get '/:id' => 'users#show', as: 'vanity'
end

app/views/layouts/_left_panel.html.haml
- if left_panel_content == :feeds
  .well
    %ul.nav.nav-list
      %li.nav-header= Collectrbot
      %li{ class: @viewing == "new" ? "active" : "" }= link_to "New", root_url(v: "new")
      %li{ class: @viewing == "shared" ? "active" : "" }= link_to "Shared", root_url(v: "shared")
      %li{ class: @viewing == "favorites" ? "active" : "" }= link_to "Favorites", root_url(v: "favorites")
      %li{ class: @viewing == "archived" ? "active" : "" }= link_to "Archived", root_url(v: "archived")
      %li{ class: @viewing == "trash" ? "active" : "" }= link_to "Trash", root_url(v: "trash")
  .well
    %ul.nav.nav-list
      %li.nav-header Friends & Followers
      - current_user.subscriptions.each do |sub|
        %li{ class: @viewing == sub.username ? "active" : "" }= link_to sub.username, vanity_path(sub)
- elsif left_panel_content == :help
  .well
    %ul.nav.nav-list
      %li.nav-header= Collectrbot
      %li= link_to "What is Collectrbot?", help_path
- elsif left_panel_content == :account
  .well
    %ul.nav.nav-list
      %li.nav-header Your Settings
      %li{ class: @viewing == "username" ? "active" : "" }= link_to "Username", edit_user_path(current_user, v: "username")
      %li{ class: @viewing == "emailpwd" ? "active" : "" }= link_to "Email and Password", edit_user_path(v: "emailpwd")
      %li{ class: @viewing == "settings" ? "active" : "" }= link_to "Settings", edit_user_path(v: "settings")
      %li{ class: @viewing == "delete" ? "active" : "" }= link_to "Delete Account", edit_user_path(v: "delete")
      %li= link_to "Help", help_path
- elsif left_panel_content != :hidden
  - raise "No panel specified"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Collectrbot"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "application"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          = link_to "Collectrbot", root_url, class: "brand"
          .container.nav-collapse
            %ul.nav.pull-right
              %li= link_to "Help", help_path
              - if user_signed_in?
                %li= link_to current_user.username, vanity_path(current_user)
                %li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Sign In", new_user_session_path
                %li= link_to "Join", new_user_registration_path
    .container-fluid

      .row-fluid
        .span3
          - if current_user
            = render "layouts/left_panel"
        .span6
          = bootstrap_flash
          = yield
        .span3
    - if Rails.env == "production"
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-42288250-1', 'collectrbot.com');
        ga('send', 'pageview');